// lib/src/models/property_model.dart

class PropertyModel {
  String? id; // Nullable as it's generated by backend
  String propertyTitle;
  String detailedDescription;
  String? coverImageUrl; // Nullable initially, updated after upload
  double rent;
  String locationId; // Assuming this might be a string ID or name from a dropdown
  double latitude; // For geocoded location
  double longitude; // For geocoded location
  String status; // e.g., 'available', 'rented'
  String userId; // Foreign key, landlord's ID
  String propertyTypesId; // Foreign key, e.g., 'apartment', 'house'
  DateTime? createdDate; // Nullable as generated by backend
  DateTime? updatedDate; // Nullable as generated by backend
  bool isActive; // Default true for new listings

  PropertyModel({
    this.id,
    required this.propertyTitle,
    required this.detailedDescription,
    this.coverImageUrl,
    required this.rent,
    required this.locationId,
    required this.latitude,
    required this.longitude,
    required this.status,
    required this.userId,
    required this.propertyTypesId,
    this.createdDate,
    this.updatedDate,
    this.isActive = true, // Default to active
  });

  // Convert a PropertyModel object into a JSON map
  Map<String, dynamic> toJson() {
    return {
      'property_title': propertyTitle,
      'detailed_description': detailedDescription,
      'cover_image_url': coverImageUrl, // Will be null or updated later
      'rent': rent,
      'location_id': locationId,
      'latitude': latitude,
      'longitude': longitude,
      'status': status,
      'user_id': userId,
      'property_types_id': propertyTypesId,
      'is_active': isActive,
      // id, created_date, updated_date are usually set by the backend
    };
  }

  // Create a PropertyModel object from a JSON map (useful for fetching existing data)
  factory PropertyModel.fromJson(Map<String, dynamic> json) {
    return PropertyModel(
      id: json['id'] as String?,
      propertyTitle: json['property_title'] as String,
      detailedDescription: json['detailed_description'] as String,
      coverImageUrl: json['cover_image_url'] as String?,
      rent: (json['rent'] as num).toDouble(),
      locationId: json['location_id'] as String,
      latitude: (json['latitude'] as num).toDouble(),
      longitude: (json['longitude'] as num).toDouble(),
      status: json['status'] as String,
      userId: json['user_id'] as String,
      propertyTypesId: json['property_types_id'] as String,
      createdDate: json['created_date'] != null
          ? DateTime.parse(json['created_date'] as String)
          : null,
      updatedDate: json['updated_date'] != null
          ? DateTime.parse(json['updated_date'] as String)
          : null,
      isActive: json['is_active'] as bool,
    );
  }
}